
/*=========================================================================*/
*	PROGRAM NAME:	eHARS Descriptive Analysis #.#				 			;
*																		    ;
*	PROJECT TITLE:	Road to Zero										 	;
*																		    ;
*	PURPOSE:		This SAS program is an example of the type of analysis	;
*					that can be conducted using the synthetic data set that ;
*					is generated by this colloection of code. To start, an 	;
*					initial DATA step is used to categorize	eHARS variables ;
*					for analysis. The following	time-to-event analysis uses ;
*					time to viral suppression as our primary interest, and 	;
*					follow-ip analyses using year of HIV diagnosis and 		;
*					gender.													; 
*																		    ;
*	GRANT SUPPORT:														 	;
*		NIH/NHAID	R01AI142690											 	;
*		UAB CFAR	P30 AI027767-31										 	;
*																		    ;
*	CREATED BY:		John Bassler										 	;
*	CONTACT INFO: 	jbassle1@uab.edu									 	;
*																		    ;
*	PURPOSE:		The success of Ending the HIV Epidemic: A Plan for 	 	;
*					America or (EHE) will depend on innovative, targeted,	; 
*					population specific interventions. Achieving early 	 	;
*					and sustained viral suppression following diagnosis  	;
*					of HIV infection is critical to improving outcomes 	 	;
*					for persons living with HIV and reducing 			 	;
*					transmission.  A deeper understanding of the 		 	;
*					socio-contextual factors driving geographic 		 	;
*					variability of VS can also guide the development of  	;
*					evidence-informed public health approaches to achieve	;
*					timely individual and population viral control. This 	;
*					simulation is designed to randomly create realistic  	;
*					geographic components that could exist in eHARS data 	;
*					for each state, while accounting for the variability 	;
*					in this data that occurs over time. The simulated 	 	;
*					data created in this program can allow for researchers	;
*					to troubleshoot development of analytic methods, 	 	;
*					while reducing the time needed from their public 	 	;
*					health department partners.							 	;
*																		    ;
*	OPERATING SYSTEM COMPATIBILITY:										 	;
* 	UNIX SAS v9.4M3-M6 		YES										 	 	;
* 	PC SAS   v9.4M3-M6      YES											 	;
*																		    ;
*	DATE CREATED:	3/08/2022											 	;
*	DATE UPDATED:														 	;
*																		    ;
*	VERSION UPDATES:													 	;
*																		    ;
*																		    ;
*																		    ;
*																		    ;
*	DISCLAIMER		This program is free to use, redistribute, and/or 	 	;
*					modify under the terms of the GNU General Public  	 	;
*					License, published by the Free Software Foundation.  	;
*					See the GNU General Public License for more details. 	;
*																		    ;
*					https://www.gnu.org/licenses/gpl-3.0.en.html		 	;
*																		    ;
*					This program is distributed with hope that you will	 	;
*					find it useful, and is open for collaboration. 		 	;
*					Please note that while distributed in good faith,  	 	;
*					this program is WITHOUT ANY WARRANTY - without even  	;
*					the implied warranty of MERCHANTABILITY or FITNESS 	 	;
*					FOR A PARTICULAR PURPOSE. 							 	;
*																		    ;
/*=========================================================================*/




%let 		site = SIMULATION;

options 	dlcreatedir; 
libname out 			"C:\Users\johnr\OneDrive\Desktop\Work\Road to Zero\Work\Simulation\Call &Sysdate.";
libname datasend 		"C:\Users\johnr\OneDrive\Desktop\Work\Road to Zero\Work\Simulation\Call &Sysdate.\Datasend &Sysdate.";
libname dataout 		"C:\Users\johnr\OneDrive\Desktop\Work\Road to Zero\Work\Simulation\Call 11APR22\Data";
libname output 			"C:\Users\johnr\OneDrive\Desktop\Work\Road to Zero\Work\Simulation\Call &Sysdate.\Output &Sysdate.";
%let location_output =   C:\Users\johnr\OneDrive\Desktop\Work\Road to Zero\Work\Simulation\Call &Sysdate.\Output &Sysdate.;
filename 	log      	"&location_output\Analysis Log &Sysdate..log";

option nofmterr;


/*=======================================================================================================================*/
/*=======================================================================================================================*/
/*=======================================================================================================================*/


data person_analysis;
	set dataout.person_analysis;
	format sex sex. 		grace grace. 	mode mode. 		mode2 modee. 		age_grp2 age_grpp. 
		   stage3 stagex. 	PHD PHD. 		dxyr dxyr. 		dfname dfname. 		suppression_month_cat_2 vs_cat.
		   method method.	aids_insure insure.				hiv_insure insure.  current_gender $c_gender.
		   edu_cat edu.	    PHD PHD.						meth meth.			gender $c_gender.;

	/* Transmission Category */
  		 if trans_categ in('01','03') then method = 1; 			/*MSM*/
  	else if trans_categ in('02') 	  then method = 2; 			/*IDU*/
  	else if trans_categ in('05')  	  then method = 3; 			/*Het*/
  	else if trans_categ in('09','10') then method = 4; 			/*Unk*/
  	else                            	   method = 5; 			/*Oth*/

  		 if trans_categ in('01','03') then meth = 1; 			/*MSM*/
  	else if trans_categ in('02') 	  then meth = 2; 			/*IDU*/
  	else if trans_categ in('05')  	  then meth = 3; 			/*Het*/
  	else 								   meth = 4; 			/*Unk&Oth*/

		 if aids_insurance in('01','02','03','04','05','06','14','11','12','13') then aids_insure = 1; /*Pub*/
	else if aids_insurance in('07','08','09') 									then aids_insure = 2;  /*Pri*/
	else if aids_insurance in('10') 											then aids_insure = 3;  /*Self*/
	else if aids_insurance in('15') 											then aids_insure = 4;  /*None*/
	else if aids_insurance in('88') 											then aids_insure = 5;  /*Oth*/
	else 							 												 aids_insure = 6;  /*Unk*/

		 if hiv_insurance in('01','02','03','04','05','06','14','11','12','13') then hiv_insure = 1;   /*Pub*/
	else if hiv_insurance in('07','08','09') 									then hiv_insure = 2;   /*Pri*/
	else if hiv_insurance in('10') 												then hiv_insure = 3;   /*Self*/
	else if hiv_insurance in('15') 												then hiv_insure = 4;   /*None*/
	else if hiv_insurance in('88') 												then hiv_insure = 5;   /*Oth*/
	else if hiv_insurance in('99') 												then hiv_insure = 6;   /*Unk*/

		 if education in('1','2') then edu_cat = 1; 
	else if education in('3') 	  then edu_cat = 2; 
	else if education in('4') 	  then edu_cat = 3;
	else if education in('5','6') then edu_cat = 4; 
	else 							   edu_cat = 5; 

		 if current_gender in("MF","FM") then gender = "T";
	else 							   		  gender = birth_sex;

	age_cont = input(hiv_aids_age_yrs, 8.);
	overall = "&site.";
	overall2 = 1;

	label overall					=	"Overall";
	label overall2					=	"Overall";
	label method 					= 	"Method of Transmission";
	label sex 						= 	"Gender at Birth (Sex)";
	label grace 					= 	"Race/Ethnicity";
	label age_grp2 					= 	"Age Group at HIV Diagnosis";
	label stage3 					= 	"Stage";
	label PHD 						= 	"Public Health District";
	label dxyr 						= 	"Year of Diagnosis";
	label dfname 					= 	"Diagnosing Facility";
	label suppression_month_cat_2 	= 	"Time to VS Group";
	label aids_insure				=	"Primary Insurance (AIDS)";
	label hiv_insure				=	"Primary Insurance (HIV)";
	label current_gender			=	"Current Gender";
	label age_cont					=	"Age at HIV Diagnosis";
	label edu_cat					=	"Highest Level of Education";
	label meth 						= 	"Method of Transmission";
	label gender 					= 	"Gender";
run;


/*=======================================================================================================================*/
/*=======================================================================================================================*/
/*=======================================================================================================================*/

ods rtf file  = "&location_output\Survival - Time to Viral Suppression overall.rtf"  
		startpage = no;

		TITLE;
		%lifetest_over(DATA 	=	person_analysis, 
				  	   OUTSURV	=	lifetest_overallb,
				  	   MEDIAN 	=	median_overallb, 
				  	   CONFTYPE	= 	LOGLOG,
				  	   NOPRINT 	= 	,
				  	   TIME		=	Time2sup,
				  	   CENSOR	=	Censor4sup(1),
				  	   TITLE 	=	"Survival - Viral Suppression overall (b)");

ods rtf close;


/*=======================================================================================================================*/
/*=======================================================================================================================*/
/*=======================================================================================================================*/


ods rtf file  = "&location_output\Survival - Time to Viral Suppression by Year of Diagnosis.rtf"  
		startpage = no;

/* SURVIVAL Year of Diagnosis*/
		TITLE;
		%lifetest(DATA 		=	person_analysis, 
				  VAR1		=	dxyr,
				  FORMAT1	=	dxyr.,	
				  OUTSURV	=	lifetest_dxyr,
				  MEDIAN 	=	median_dxyr, 
				  CONFTYPE	= 	LOGLOG,
				  NOPRINT 	= 	,
				  TIME		=	Time2sup,
				  CENSOR	=	Censor4sup(1),
				  TITLE 	=	"Survival - Viral Suppression by Year of Diagnosis");

ods rtf close;


/*=======================================================================================================================*/
/*=======================================================================================================================*/
/*=======================================================================================================================*/


proc sort data = person_analysis; by dxyr Gender; run;

ods rtf file  = "&location_output\Survival - Time to Viral Suppression by Gender.rtf"  
		startpage = no;

/* SURVIVAL GENDER*/

		TITLE;
		%lifetest(DATA 		=	person_analysis, 
				  VAR1		=	Gender,
				  FORMAT1	=	$c_gender.,	
				  OUTSURV	=	lifetest_Gender,
 		  		  MEDIAN 	=	median_Gender,
				  CONFTYPE	= 	LOGLOG,
				  NOPRINT 	= 	,
				  TIME		=	Time2sup,
				  CENSOR	=	Censor4sup(1),
				  TITLE 	=	"Survival - Time to Viral Suppression by Gender");

ods rtf close;


/*======================================================================================================================*/


ods rtf file  = "&location_output\Survival - Time to Viral Suppression by Gender and Year of Diagnosis.rtf"  
		startpage = no;

/* Survival GENDER x DXYR */

		TITLE;
		%lifetest_panel(DATA 		=	person_analysis, 
				  	    VAR1		=	Gender,
				  	    FORMAT1		=	$c_gender.,	
					    VAR2 		= 	dxyr, 
					    FORMAT2 	= 	dxyr., 
				  	    OUTSURV		=	lifetest_gender_by_year,
				  		MEDIAN 		=	median_gender_by_year,
				  	    CONFTYPE	= 	LOGLOG,
				  	    NOPRINT 	= 	,
				  	    TIME		=	Time2sup,
				  	    CENSOR		=	Censor4sup(1),
				  	    TITLE 		=	"Survival - Time to Viral Suppression by Gender and Year of Diagnosis");

ods rtf close;

/*=======================================================================================================================*/

ods rtf file  = "&location_output\Time to Viral Suppression Category by Gender.rtf"  
		startpage = no;

/* Suppression Category Table GENDER */

		TITLE;
		%vs_cat(TITLE 	= 'Time to Viral Suppression Category by Gender', 
				DATA 	= person_analysis_2, 
				VAR1 	= Gender, 
				FORMAT1 = $c_gender., 
				VAR2	= dxyr, 
				FORMAT2 = dxyr., 
				OUT 	= vs_cat_Gender);

ods rtf close;


/*=======================================================================================================================*/
/*=======================================================================================================================*/
/*=======================================================================================================================*/


dm "log; print file = log	replace;";

